name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Free up disk space
      run: |
        echo "Freeing up disk space..."
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo docker system prune -a -f
        sudo rm -rf /home/runner/work/*

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t centilebrain/halfpipe_test .

    - name: Push Docker image to Docker Hub
      run: docker push centilebrain/halfpipe_test
